### ISSUE TITLE
Rework doc now that the cli documentation is available

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/galasa.dev#591]
[x] move the CLI section above the Eclipse section
       [x] Getting started with the CLI, installing, initialising, creating, running
[x] remove the runs prepare and runs submit from toc level entries
[x] add a reference section for the Javadoc and the CLI commands
[x] update Windows commands - change ^ to ` and galasasctl to galasactl.exe

**Comment by techcobweb** [comment]
Turns out that if you put an .exe on the windows PATH, then you don't have to use the `.exe` in the name when you invoke it. So we can probably just say on the install instructions that they should add it to their PATH, and then the command-line examples can drop the `.exe` extension. Does that make sense ?

Also, where we say "Windows", we probably need to say "Windows (Powershell)" , as the line-continuation characters for windows 'cmd' shell are '^' characters.

**Comment by CaroMac** [comment]
Just messaged Mike to clarify updates.

**Comment by CaroMac** [comment]
have made updates, moving to review

**Comment by techcobweb** [comment]
This is complete now ?
